# This is a TOML document. Boom

[Base]
    ProfPathPrefix= "debug"
    LogLevel= "debug"
    ProfEnable= true
    TracerEnable= true
    WhiteList= [""]
    Endpoints= [":0"]

[Discovery]
    endpoints = ["127.0.0.1:2379"]

[RpcServer]
    timeout = "1s"
    addr = "127.0.0.1:10631"

[Event]
    Source = "loopback://memqueue/event/allinone"

[etcd]
    endpoints = ["127.0.0.1:2379"]

[redis]
    network = "tcp"
    addr = "127.0.0.1:6379"
    auth = "qingcloud2019"
    maxActive = 8
    dialTimeout = "3s"
    readTimeout = "1s"
    writeTimeout = "1s"
    idleTimeout = "120s"
    poolTimeout = "30m"

[Jaeger]
    addr = "127.0.0.1:6831"

[Slot]
    RuleSource = "loopback://memqueue/topic/allinone"
    PubSubSource = "loopback://memqueue/topic/allinone"
    PubSubSink = "loopback://memqueue/queue/allinone"